# Loads all the necessary functions in the fcns folder
include("../fcns/fcn_locate.jl")
include("../fcns/fcn_makeweights.jl")
include("../fcns/parameters.jl")
include("../fcns/fcn_shocks.jl")
include("../fcns/fcn_maketransition.jl")
include("../fcns/fcn_simulate.jl")
include("../fcns/fcn_Fdistr.jl")
include("../fcns/fcn_util_etc.jl")
include("../fcns/fcn_interpols.jl")
include("../fcns/EGM_policyupdate.jl")
include("../fcns/fcn_update.jl")
include("../fcns/fcn_solve_HH.jl")
include("../fcns/fcn_FastRoot.jl")
include("../fcns/fcn_perceived.jl")
